AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-sqs-dlq-redriver
    Description: This serverless application redrives the messages from an SQS DLQ back to its source SQS queue.
    Author: Lu Hong
    SpdxLicenseId: MIT
    # paths are relative to .aws-sam/build directory
    LicenseUrl: ../../LICENSE
    ReadmeUrl: ../../README.md
    Labels: [serverless, SQS]
    HomePageUrl: https://github.com/honglu/aws-sqs-dlq-redriver
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/honglu/aws-sqs-dlq-redriver/tree/0.0.1

Parameters:
  LogLevel:
    Type: String
    Description: Log level for Lambda function logging, e.g., ERROR, INFO, DEBUG, etc
    Default: INFO

Resources:
  SQSDLQRedriver:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: myfunction.handler
      Runtime: python3.7
      Tracing: Active
      Timeout: 60
      MemorySize: 768
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:SendMessage
            - sqs:DeleteMessage
            - sqs:ListDeadLetterSourceQueues
            Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*'

Outputs:
  SQSDLQRedriverName:
    Description: "SQS DLQ Redriver Lambda Function Name"
    Value: !Ref SQSDLQRedriver
  SQSDLQRedriverArn:
    Description: "SQS DLQ Redriver Lambda Function ARN"
    Value: !GetAtt SQSDLQRedriver.Arn
