AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-sqs-dlq-redriver
    Description: This serverless application redrives the messages from an SQS DLQ back to its main SQS queue.
    Author: Lu Hong
    SpdxLicenseId: MIT
    # paths are relative to .aws-sam/build directory
    LicenseUrl: ../../LICENSE
    ReadmeUrl: ../../README.md
    Labels: [serverless]
    HomePageUrl: https://github.com/honglu/aws-sqs-dlq-redriver
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/honglu/aws-sqs-dlq-redriver/tree/0.0.1

Parameters:
  LogLevel:
    Type: String
    Description: Log level for Lambda function logging, e.g., ERROR, INFO, DEBUG, etc
    Default: INFO

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: myfunction.handler
      Runtime: python3.7
      Tracing: Active
      Timeout: 60
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          TABLE_NAME: !Ref MyTable

  MyTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  MyFunctionName:
    Description: "Lambda Function Name"
    Value: !Ref MyFunction
  MyFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt MyFunction.Arn
  MyTableName:
    Description: "Table Name"
    Value: !Ref MyTable
  MyTableArn:
    Description: "Table ARN"
    Value: !GetAtt MyTable.Arn
